### ISSUE TITLE
TopHat als .step file?

### ISSUE THREAD

**Issue by wuzefacke** [Drachenkaetzchen/VoronMods#1]
Hey,
besteht die Möglichkeit, den TopHat als .step File zur Verfügung zu stellen?
Würde da gerne etwas experimentieren und eine Display Halterung bauen.
https://github.com/Drachenkaetzchen/VoronMods/tree/main/TopHat
Danke Dir

**Comment by Drachenkaetzchen** [comment]
Nein ist nicht möglich, da OpenSCAD kein STEP kann.
